### ISSUE TITLE
ToDo db Gear Set Bonus

### ISSUE THREAD

**Issue by Thecarlosmff** [Thecarlosmff/DC-Legends-Tools#2]
# Table GearAtrib

- [ ] Mixed Support LV1  SLOT 1
- [ ] Mixed Support LV1  SLOT 2
- [ ] Mixed Support LV1  SLOT 3
- [ ] Mixed Support LV1  SLOT 4
- [ ] Mixed Support LV1  SLOT 5
- [ ] Mixed Support LV1  SLOT 6
- [ ] Mixed Support LV2  SLOT 1
- [ ] Mixed Support LV2  SLOT 2
- [ ] Mixed Support LV2  SLOT 3
- [ ] Mixed Support LV2  SLOT 4
- [ ] Mixed Support LV2  SLOT 5
- [ ] Mixed Support LV2  SLOT 6
- [ ] Mixed Support LV3  SLOT 1
- [ ] Mixed Support LV3  SLOT 2
- [ ] Mixed Support LV3  SLOT 3
- [ ] Mixed Support LV3  SLOT 4
- [ ] Mixed Support LV3  SLOT 5
- [ ] Mixed Support LV3  SLOT 6
- [ ] Mixed Support LV4  SLOT 1
- [ ] Mixed Support LV4  SLOT 2
- [ ] Mixed Support LV4  SLOT 3
- [ ] Mixed Support LV4  SLOT 4
- [ ] Mixed Support LV4  SLOT 5
- [ ] Mixed Support LV4  SLOT 6
- [ ] Mixed Support LV5  SLOT 1
- [ ] Mixed Support LV5  SLOT 2
- [ ] Mixed Support LV5  SLOT 3
- [ ] Mixed Support LV5  SLOT 4
- [ ] Mixed Support LV5  SLOT 5
- [ ] Mixed Support LV5  SLOT 6
- [ ] Mixed Support LV6  SLOT 1
- [ ] Mixed Support LV6  SLOT 2
- [ ] Mixed Support LV6  SLOT 3
- [ ] Mixed Support LV6  SLOT 4
- [ ] Mixed Support LV6  SLOT 5
- [ ] Mixed Support LV6  SLOT 6
- [ ] Mixed Support LV7  SLOT 1
- [ ] Mixed Support LV7  SLOT 2
- [ ] Mixed Support LV7  SLOT 3
- [ ] Mixed Support LV7  SLOT 4
- [ ] Mixed Support LV7  SLOT 5
- [ ] Mixed Support LV7  SLOT 6
- [ ] Mixed Support LV8  SLOT 1
- [ ] Mixed Support LV8  SLOT 2
- [ ] Mixed Support LV8  SLOT 3
- [ ] Mixed Support LV8  SLOT 4
- [ ] Mixed Support LV8  SLOT 5
- [ ] Mixed Support LV8  SLOT 6
- [ ] Mixed Support LV9  SLOT 1
- [ ] Mixed Support LV9  SLOT 2
- [ ] Mixed Support LV9  SLOT 3
- [ ] Mixed Support LV9  SLOT 4
- [ ] Mixed Support LV9  SLOT 5
- [ ] Mixed Support LV9  SLOT 6
- [ ] Mixed Support LV10  SLOT 1
- [ ] Mixed Support LV10  SLOT 2
- [ ] Mixed Support LV10  SLOT 3
- [ ] Mixed Support LV10  SLOT 4
- [ ] Mixed Support LV10  SLOT 5
- [ ] Mixed Support LV10  SLOT 6
- [ ] Mixed Support LV11  SLOT 1
- [ ] Mixed Support LV11  SLOT 2
- [ ] Mixed Support LV11  SLOT 3
- [ ] Mixed Support LV11  SLOT 4
- [ ] Mixed Support LV11  SLOT 5
- [ ] Mixed Support LV11  SLOT 6
- [ ] Mixed Tank LV1  SLOT 1
- [ ] Mixed Tank LV1  SLOT 2
- [ ] Mixed Tank LV1  SLOT 3
- [ ] Mixed Tank LV1  SLOT 4
- [ ] Mixed Tank LV1  SLOT 5
- [ ] Mixed Tank LV1  SLOT 6
- [ ] Mixed Tank LV2  SLOT 1
- [ ] Mixed Tank LV2  SLOT 2
- [ ] Mixed Tank LV2  SLOT 3
- [ ] Mixed Tank LV2  SLOT 4
- [ ] Mixed Tank LV2  SLOT 5
- [ ] Mixed Tank LV2  SLOT 6
- [ ] Mixed Tank LV3  SLOT 1
- [ ] Mixed Tank LV3  SLOT 2
- [ ] Mixed Tank LV3  SLOT 3
- [ ] Mixed Tank LV3  SLOT 4
- [ ] Mixed Tank LV3  SLOT 5
- [ ] Mixed Tank LV3  SLOT 6
- [ ] Mixed Tank LV4  SLOT 1
- [ ] Mixed Tank LV4  SLOT 2
- [ ] Mixed Tank LV4  SLOT 3
- [ ] Mixed Tank LV4  SLOT 4
- [ ] Mixed Tank LV4  SLOT 5
- [ ] Mixed Tank LV4  SLOT 6
- [ ] Mixed Tank LV5  SLOT 1
- [ ] Mixed Tank LV5  SLOT 2
- [ ] Mixed Tank LV5  SLOT 3
- [ ] Mixed Tank LV5  SLOT 4
- [ ] Mixed Tank LV5  SLOT 5
- [ ] Mixed Tank LV5  SLOT 6
- [ ] Mixed Tank LV6  SLOT 1
- [ ] Mixed Tank LV6  SLOT 2
- [ ] Mixed Tank LV6  SLOT 3
- [ ] Mixed Tank LV6  SLOT 4
- [ ] Mixed Tank LV6  SLOT 5
- [ ] Mixed Tank LV6  SLOT 6
- [ ] Mixed Tank LV7  SLOT 1
- [ ] Mixed Tank LV7  SLOT 2
- [ ] Mixed Tank LV7  SLOT 3
- [ ] Mixed Tank LV7  SLOT 4
- [ ] Mixed Tank LV7  SLOT 5
- [ ] Mixed Tank LV7  SLOT 6
- [ ] Mixed Tank LV8  SLOT 1
- [ ] Mixed Tank LV8  SLOT 2
- [ ] Mixed Tank LV8  SLOT 3
- [ ] Mixed Tank LV8  SLOT 4
- [ ] Mixed Tank LV8  SLOT 5
- [ ] Mixed Tank LV8  SLOT 6
- [ ] Mixed Tank LV9  SLOT 1
- [ ] Mixed Tank LV9  SLOT 2
- [ ] Mixed Tank LV9  SLOT 3
- [ ] Mixed Tank LV9  SLOT 4
- [ ] Mixed Tank LV9  SLOT 5
- [ ] Mixed Tank LV9  SLOT 6
- [ ] Mixed Tank LV10  SLOT 1
- [ ] Mixed Tank LV10  SLOT 2
- [ ] Mixed Tank LV10  SLOT 3
- [ ] Mixed Tank LV10  SLOT 4
- [ ] Mixed Tank LV10  SLOT 5
- [ ] Mixed Tank LV10  SLOT 6
- [ ] Mixed Tank LV11  SLOT 1
- [ ] Mixed Tank LV11  SLOT 2
- [ ] Mixed Tank LV11  SLOT 3
- [ ] Mixed Tank LV11  SLOT 4
- [ ] Mixed Tank LV11  SLOT 5
- [ ] Mixed Tank LV11  SLOT 6
- [ ] Mixed Striker LV1  SLOT 1
- [ ] Mixed Striker LV1  SLOT 2
- [ ] Mixed Striker LV1  SLOT 3
- [ ] Mixed Striker LV1  SLOT 4
- [ ] Mixed Striker LV1  SLOT 5
- [ ] Mixed Striker LV1  SLOT 6
- [ ] Mixed Striker LV2  SLOT 1
- [ ] Mixed Striker LV2  SLOT 2
- [ ] Mixed Striker LV2  SLOT 3
- [ ] Mixed Striker LV2  SLOT 4
- [ ] Mixed Striker LV2  SLOT 5
- [ ] Mixed Striker LV2  SLOT 6
- [ ] Mixed Striker LV3  SLOT 1
- [ ] Mixed Striker LV3  SLOT 2
- [ ] Mixed Striker LV3  SLOT 3
- [ ] Mixed Striker LV3  SLOT 4
- [ ] Mixed Striker LV3  SLOT 5
- [ ] Mixed Striker LV3  SLOT 6
- [ ] Mixed Striker LV4  SLOT 1
- [ ] Mixed Striker LV4  SLOT 2
- [ ] Mixed Striker LV4  SLOT 3
- [ ] Mixed Striker LV4  SLOT 4
- [ ] Mixed Striker LV4  SLOT 5
- [ ] Mixed Striker LV4  SLOT 6
- [ ] Mixed Striker LV5  SLOT 1
- [ ] Mixed Striker LV5  SLOT 2
- [ ] Mixed Striker LV5  SLOT 3
- [ ] Mixed Striker LV5  SLOT 4
- [ ] Mixed Striker LV5  SLOT 5
- [ ] Mixed Striker LV5  SLOT 6
- [ ] Mixed Striker LV6  SLOT 1
- [ ] Mixed Striker LV6  SLOT 2
- [ ] Mixed Striker LV6  SLOT 3
- [ ] Mixed Striker LV6  SLOT 4
- [ ] Mixed Striker LV6  SLOT 5
- [ ] Mixed Striker LV6  SLOT 6
- [ ] Mixed Striker LV7  SLOT 1
- [ ] Mixed Striker LV7  SLOT 2
- [ ] Mixed Striker LV7  SLOT 3
- [ ] Mixed Striker LV7  SLOT 4
- [ ] Mixed Striker LV7  SLOT 5
- [ ] Mixed Striker LV7  SLOT 6
- [ ] Mixed Striker LV8  SLOT 1
- [ ] Mixed Striker LV8  SLOT 2
- [ ] Mixed Striker LV8  SLOT 3
- [ ] Mixed Striker LV8  SLOT 4
- [ ] Mixed Striker LV8  SLOT 5
- [ ] Mixed Striker LV8  SLOT 6
- [ ] Mixed Striker LV9  SLOT 1
- [ ] Mixed Striker LV9  SLOT 2
- [ ] Mixed Striker LV9  SLOT 3
- [ ] Mixed Striker LV9  SLOT 4
- [ ] Mixed Striker LV9  SLOT 5
- [ ] Mixed Striker LV9  SLOT 6
- [ ] Mixed Striker LV10  SLOT 1
- [ ] Mixed Striker LV10  SLOT 2
- [ ] Mixed Striker LV10  SLOT 3
- [ ] Mixed Striker LV10  SLOT 4
- [ ] Mixed Striker LV10  SLOT 5
- [ ] Mixed Striker LV10  SLOT 6
- [ ] Mixed Striker LV11  SLOT 1
- [ ] Mixed Striker LV11  SLOT 2
- [ ] Mixed Striker LV11  SLOT 3
- [ ] Mixed Striker LV11  SLOT 4
- [ ] Mixed Striker LV11  SLOT 5
- [ ] Mixed Striker LV11  SLOT 6
- [ ] Physical Support LV1  SLOT 1
- [ ] Physical Support LV1  SLOT 2
- [ ] Physical Support LV1  SLOT 3
- [ ] Physical Support LV1  SLOT 4
- [ ] Physical Support LV1  SLOT 5
- [ ] Physical Support LV1  SLOT 6
- [ ] Physical Support LV2  SLOT 1
- [ ] Physical Support LV2  SLOT 2
- [ ] Physical Support LV2  SLOT 3
- [ ] Physical Support LV2  SLOT 4
- [ ] Physical Support LV2  SLOT 5
- [ ] Physical Support LV2  SLOT 6
- [ ] Physical Support LV3  SLOT 1
- [ ] Physical Support LV3  SLOT 2
- [ ] Physical Support LV3  SLOT 3
- [ ] Physical Support LV3  SLOT 4
- [ ] Physical Support LV3  SLOT 5
- [ ] Physical Support LV3  SLOT 6
- [ ] Physical Support LV4  SLOT 1
- [ ] Physical Support LV4  SLOT 2
- [ ] Physical Support LV4  SLOT 3
- [ ] Physical Support LV4  SLOT 4
- [ ] Physical Support LV4  SLOT 5
- [ ] Physical Support LV4  SLOT 6
- [ ] Physical Support LV5  SLOT 1
- [ ] Physical Support LV5  SLOT 2
- [ ] Physical Support LV5  SLOT 3
- [ ] Physical Support LV5  SLOT 4
- [ ] Physical Support LV5  SLOT 5
- [ ] Physical Support LV5  SLOT 6
- [ ] Physical Support LV6  SLOT 1
- [ ] Physical Support LV6  SLOT 2
- [ ] Physical Support LV6  SLOT 3
- [ ] Physical Support LV6  SLOT 4
- [ ] Physical Support LV6  SLOT 5
- [ ] Physical Support LV6  SLOT 6
- [ ] Physical Support LV7  SLOT 1
- [ ] Physical Support LV7  SLOT 2
- [ ] Physical Support LV7  SLOT 3
- [ ] Physical Support LV7  SLOT 4
- [ ] Physical Support LV7  SLOT 5
- [ ] Physical Support LV7  SLOT 6
- [ ] Physical Support LV8  SLOT 1
- [ ] Physical Support LV8  SLOT 2
- [ ] Physical Support LV8  SLOT 3
- [ ] Physical Support LV8  SLOT 4
- [ ] Physical Support LV8  SLOT 5
- [ ] Physical Support LV8  SLOT 6
- [ ] Physical Support LV9  SLOT 1
- [ ] Physical Support LV9  SLOT 2
- [ ] Physical Support LV9  SLOT 3
- [ ] Physical Support LV9  SLOT 4
- [ ] Physical Support LV9  SLOT 5
- [ ] Physical Support LV9  SLOT 6
- [ ] Physical Support LV10  SLOT 1
- [ ] Physical Support LV10  SLOT 2
- [ ] Physical Support LV10  SLOT 3
- [ ] Physical Support LV10  SLOT 4
- [ ] Physical Support LV10  SLOT 5
- [ ] Physical Support LV10  SLOT 6
- [ ] Physical Support LV11  SLOT 1
- [ ] Physical Support LV11  SLOT 2
- [ ] Physical Support LV11  SLOT 3
- [ ] Physical Support LV11  SLOT 4
- [ ] Physical Support LV11  SLOT 5
- [ ] Physical Support LV11  SLOT 6
- [ ] Physical Tank LV1  SLOT 1
- [ ] Physical Tank LV1  SLOT 2
- [ ] Physical Tank LV1  SLOT 3
- [ ] Physical Tank LV1  SLOT 4
- [ ] Physical Tank LV1  SLOT 5
- [ ] Physical Tank LV1  SLOT 6
- [ ] Physical Tank LV2  SLOT 1
- [ ] Physical Tank LV2  SLOT 2
- [ ] Physical Tank LV2  SLOT 3
- [ ] Physical Tank LV2  SLOT 4
- [ ] Physical Tank LV2  SLOT 5
- [ ] Physical Tank LV2  SLOT 6
- [ ] Physical Tank LV3  SLOT 1
- [ ] Physical Tank LV3  SLOT 2
- [ ] Physical Tank LV3  SLOT 3
- [ ] Physical Tank LV3  SLOT 4
- [ ] Physical Tank LV3  SLOT 5
- [ ] Physical Tank LV3  SLOT 6
- [ ] Physical Tank LV4  SLOT 1
- [ ] Physical Tank LV4  SLOT 2
- [ ] Physical Tank LV4  SLOT 3
- [ ] Physical Tank LV4  SLOT 4
- [ ] Physical Tank LV4  SLOT 5
- [ ] Physical Tank LV4  SLOT 6
- [ ] Physical Tank LV5  SLOT 1
- [ ] Physical Tank LV5  SLOT 2
- [ ] Physical Tank LV5  SLOT 3
- [ ] Physical Tank LV5  SLOT 4
- [ ] Physical Tank LV5  SLOT 5
- [ ] Physical Tank LV5  SLOT 6
- [ ] Physical Tank LV6  SLOT 1
- [ ] Physical Tank LV6  SLOT 2
- [ ] Physical Tank LV6  SLOT 3
- [ ] Physical Tank LV6  SLOT 4
- [ ] Physical Tank LV6  SLOT 5
- [ ] Physical Tank LV6  SLOT 6
- [ ] Physical Tank LV7  SLOT 1
- [ ] Physical Tank LV7  SLOT 2
- [ ] Physical Tank LV7  SLOT 3
- [ ] Physical Tank LV7  SLOT 4
- [ ] Physical Tank LV7  SLOT 5
- [ ] Physical Tank LV7  SLOT 6
- [ ] Physical Tank LV8  SLOT 1
- [ ] Physical Tank LV8  SLOT 2
- [ ] Physical Tank LV8  SLOT 3
- [ ] Physical Tank LV8  SLOT 4
- [ ] Physical Tank LV8  SLOT 5
- [ ] Physical Tank LV8  SLOT 6
- [ ] Physical Tank LV9  SLOT 1
- [ ] Physical Tank LV9  SLOT 2
- [ ] Physical Tank LV9  SLOT 3
- [ ] Physical Tank LV9  SLOT 4
- [ ] Physical Tank LV9  SLOT 5
- [ ] Physical Tank LV9  SLOT 6
- [ ] Physical Tank LV10  SLOT 1
- [ ] Physical Tank LV10  SLOT 2
- [ ] Physical Tank LV10  SLOT 3
- [ ] Physical Tank LV10  SLOT 4
- [ ] Physical Tank LV10  SLOT 5
- [ ] Physical Tank LV10  SLOT 6
- [ ] Physical Tank LV11  SLOT 1
- [ ] Physical Tank LV11  SLOT 2
- [ ] Physical Tank LV11  SLOT 3
- [ ] Physical Tank LV11  SLOT 4
- [ ] Physical Tank LV11  SLOT 5
- [ ] Physical Tank LV11  SLOT 6
- [ ] Physical Striker LV1  SLOT 1
- [ ] Physical Striker LV1  SLOT 2
- [ ] Physical Striker LV1  SLOT 3
- [ ] Physical Striker LV1  SLOT 4
- [ ] Physical Striker LV1  SLOT 5
- [ ] Physical Striker LV1  SLOT 6
- [ ] Physical Striker LV2  SLOT 1
- [ ] Physical Striker LV2  SLOT 2
- [ ] Physical Striker LV2  SLOT 3
- [ ] Physical Striker LV2  SLOT 4
- [ ] Physical Striker LV2  SLOT 5
- [ ] Physical Striker LV2  SLOT 6
- [ ] Physical Striker LV3  SLOT 1
- [ ] Physical Striker LV3  SLOT 2
- [ ] Physical Striker LV3  SLOT 3
- [ ] Physical Striker LV3  SLOT 4
- [ ] Physical Striker LV3  SLOT 5
- [ ] Physical Striker LV3  SLOT 6
- [ ] Physical Striker LV4  SLOT 1
- [ ] Physical Striker LV4  SLOT 2
- [ ] Physical Striker LV4  SLOT 3
- [ ] Physical Striker LV4  SLOT 4
- [ ] Physical Striker LV4  SLOT 5
- [ ] Physical Striker LV4  SLOT 6
- [ ] Physical Striker LV5  SLOT 1
- [ ] Physical Striker LV5  SLOT 2
- [ ] Physical Striker LV5  SLOT 3
- [ ] Physical Striker LV5  SLOT 4
- [ ] Physical Striker LV5  SLOT 5
- [ ] Physical Striker LV5  SLOT 6
- [ ] Physical Striker LV6  SLOT 1
- [ ] Physical Striker LV6  SLOT 2
- [ ] Physical Striker LV6  SLOT 3
- [ ] Physical Striker LV6  SLOT 4
- [ ] Physical Striker LV6  SLOT 5
- [ ] Physical Striker LV6  SLOT 6
- [ ] Physical Striker LV7  SLOT 1
- [ ] Physical Striker LV7  SLOT 2
- [ ] Physical Striker LV7  SLOT 3
- [ ] Physical Striker LV7  SLOT 4
- [ ] Physical Striker LV7  SLOT 5
- [ ] Physical Striker LV7  SLOT 6
- [ ] Physical Striker LV8  SLOT 1
- [ ] Physical Striker LV8  SLOT 2
- [ ] Physical Striker LV8  SLOT 3
- [ ] Physical Striker LV8  SLOT 4
- [ ] Physical Striker LV8  SLOT 5
- [ ] Physical Striker LV8  SLOT 6
- [ ] Physical Striker LV9  SLOT 1
- [ ] Physical Striker LV9  SLOT 2
- [ ] Physical Striker LV9  SLOT 3
- [ ] Physical Striker LV9  SLOT 4
- [ ] Physical Striker LV9  SLOT 5
- [ ] Physical Striker LV9  SLOT 6
- [ ] Physical Striker LV10  SLOT 1
- [ ] Physical Striker LV10  SLOT 2
- [ ] Physical Striker LV10  SLOT 3
- [ ] Physical Striker LV10  SLOT 4
- [ ] Physical Striker LV10  SLOT 5
- [ ] Physical Striker LV10  SLOT 6
- [ ] Physical Striker LV11  SLOT 1
- [ ] Physical Striker LV11  SLOT 2
- [ ] Physical Striker LV11  SLOT 3
- [ ] Physical Striker LV11  SLOT 4
- [ ] Physical Striker LV11  SLOT 5
- [ ] Physical Striker LV11  SLOT 6
- [ ] Special Support LV1  SLOT 1
- [ ] Special Support LV1  SLOT 2
- [ ] Special Support LV1  SLOT 3
- [ ] Special Support LV1  SLOT 4
- [ ] Special Support LV1  SLOT 5
- [ ] Special Support LV1  SLOT 6
- [ ] Special Support LV2  SLOT 1
- [ ] Special Support LV2  SLOT 2
- [ ] Special Support LV2  SLOT 3
- [ ] Special Support LV2  SLOT 4
- [ ] Special Support LV2  SLOT 5
- [ ] Special Support LV2  SLOT 6
- [ ] Special Support LV3  SLOT 1
- [ ] Special Support LV3  SLOT 2
- [ ] Special Support LV3  SLOT 3
- [ ] Special Support LV3  SLOT 4
- [ ] Special Support LV3  SLOT 5
- [ ] Special Support LV3  SLOT 6
- [ ] Special Support LV4  SLOT 1
- [ ] Special Support LV4  SLOT 2
- [ ] Special Support LV4  SLOT 3
- [ ] Special Support LV4  SLOT 4
- [ ] Special Support LV4  SLOT 5
- [ ] Special Support LV4  SLOT 6
- [ ] Special Support LV5  SLOT 1
- [ ] Special Support LV5  SLOT 2
- [ ] Special Support LV5  SLOT 3
- [ ] Special Support LV5  SLOT 4
- [ ] Special Support LV5  SLOT 5
- [ ] Special Support LV5  SLOT 6
- [ ] Special Support LV6  SLOT 1
- [ ] Special Support LV6  SLOT 2
- [ ] Special Support LV6  SLOT 3
- [ ] Special Support LV6  SLOT 4
- [ ] Special Support LV6  SLOT 5
- [ ] Special Support LV6  SLOT 6
- [ ] Special Support LV7  SLOT 1
- [ ] Special Support LV7  SLOT 2
- [ ] Special Support LV7  SLOT 3
- [ ] Special Support LV7  SLOT 4
- [ ] Special Support LV7  SLOT 5
- [ ] Special Support LV7  SLOT 6
- [ ] Special Support LV8  SLOT 1
- [ ] Special Support LV8  SLOT 2
- [ ] Special Support LV8  SLOT 3
- [ ] Special Support LV8  SLOT 4
- [ ] Special Support LV8  SLOT 5
- [ ] Special Support LV8  SLOT 6
- [ ] Special Support LV9  SLOT 1
- [ ] Special Support LV9  SLOT 2
- [ ] Special Support LV9  SLOT 3
- [ ] Special Support LV9  SLOT 4
- [ ] Special Support LV9  SLOT 5
- [ ] Special Support LV9  SLOT 6
- [ ] Special Support LV10  SLOT 1
- [ ] Special Support LV10  SLOT 2
- [ ] Special Support LV10  SLOT 3
- [ ] Special Support LV10  SLOT 4
- [ ] Special Support LV10  SLOT 5
- [ ] Special Support LV10  SLOT 6
- [ ] Special Support LV11  SLOT 1
- [ ] Special Support LV11  SLOT 2
- [ ] Special Support LV11  SLOT 3
- [ ] Special Support LV11  SLOT 4
- [ ] Special Support LV11  SLOT 5
- [ ] Special Support LV11  SLOT 6
- [ ] Special Striker LV1  SLOT 1
- [ ] Special Striker LV1  SLOT 2
- [ ] Special Striker LV1  SLOT 3
- [ ] Special Striker LV1  SLOT 4
- [ ] Special Striker LV1  SLOT 5
- [ ] Special Striker LV1  SLOT 6
- [ ] Special Striker LV2  SLOT 1
- [ ] Special Striker LV2  SLOT 2
- [ ] Special Striker LV2  SLOT 3
- [ ] Special Striker LV2  SLOT 4
- [ ] Special Striker LV2  SLOT 5
- [ ] Special Striker LV2  SLOT 6
- [ ] Special Striker LV3  SLOT 1
- [ ] Special Striker LV3  SLOT 2
- [ ] Special Striker LV3  SLOT 3
- [ ] Special Striker LV3  SLOT 4
- [ ] Special Striker LV3  SLOT 5
- [ ] Special Striker LV3  SLOT 6
- [ ] Special Striker LV4  SLOT 1
- [ ] Special Striker LV4  SLOT 2
- [ ] Special Striker LV4  SLOT 3
- [ ] Special Striker LV4  SLOT 4
- [ ] Special Striker LV4  SLOT 5
- [ ] Special Striker LV4  SLOT 6
- [ ] Special Striker LV5  SLOT 1
- [ ] Special Striker LV5  SLOT 2
- [ ] Special Striker LV5  SLOT 3
- [ ] Special Striker LV5  SLOT 4
- [ ] Special Striker LV5  SLOT 5
- [ ] Special Striker LV5  SLOT 6
- [ ] Special Striker LV6  SLOT 1
- [ ] Special Striker LV6  SLOT 2
- [ ] Special Striker LV6  SLOT 3
- [ ] Special Striker LV6  SLOT 4
- [ ] Special Striker LV6  SLOT 5
- [ ] Special Striker LV6  SLOT 6
- [ ] Special Striker LV7  SLOT 1
- [ ] Special Striker LV7  SLOT 2
- [ ] Special Striker LV7  SLOT 3
- [ ] Special Striker LV7  SLOT 4
- [ ] Special Striker LV7  SLOT 5
- [ ] Special Striker LV7  SLOT 6
- [ ] Special Striker LV8  SLOT 1
- [ ] Special Striker LV8  SLOT 2
- [ ] Special Striker LV8  SLOT 3
- [ ] Special Striker LV8  SLOT 4
- [ ] Special Striker LV8  SLOT 5
- [ ] Special Striker LV8  SLOT 6
- [ ] Special Striker LV9  SLOT 1
- [ ] Special Striker LV9  SLOT 2
- [ ] Special Striker LV9  SLOT 3
- [ ] Special Striker LV9  SLOT 4
- [ ] Special Striker LV9  SLOT 5
- [ ] Special Striker LV9  SLOT 6
- [x] Special Striker LV10  SLOT 1
- [x] Special Striker LV10  SLOT 2
- [x] Special Striker LV10  SLOT 3
- [x] Special Striker LV10  SLOT 4
- [x] Special Striker LV10  SLOT 5
- [x] Special Striker LV10  SLOT 6
- [ ] Special Striker LV11  SLOT 1
- [ ] Special Striker LV11  SLOT 2
- [ ] Special Striker LV11  SLOT 3
- [ ] Special Striker LV11  SLOT 4
- [ ] Special Striker LV11  SLOT 5
- [ ] Special Striker LV11  SLOT 6
- [ ] Special Tank LV1  SLOT 1
- [ ] Special Tank LV1  SLOT 2
- [ ] Special Tank LV1  SLOT 3
- [ ] Special Tank LV1  SLOT 4
- [ ] Special Tank LV1  SLOT 5
- [ ] Special Tank LV1  SLOT 6
- [ ] Special Tank LV2  SLOT 1
- [ ] Special Tank LV2  SLOT 2
- [ ] Special Tank LV2  SLOT 3
- [ ] Special Tank LV2  SLOT 4
- [ ] Special Tank LV2  SLOT 5
- [ ] Special Tank LV2  SLOT 6
- [ ] Special Tank LV3  SLOT 1
- [ ] Special Tank LV3  SLOT 2
- [ ] Special Tank LV3  SLOT 3
- [ ] Special Tank LV3  SLOT 4
- [ ] Special Tank LV3  SLOT 5
- [ ] Special Tank LV3  SLOT 6
- [ ] Special Tank LV4  SLOT 1
- [ ] Special Tank LV4  SLOT 2
- [ ] Special Tank LV4  SLOT 3
- [ ] Special Tank LV4  SLOT 4
- [ ] Special Tank LV4  SLOT 5
- [ ] Special Tank LV4  SLOT 6
- [ ] Special Tank LV5  SLOT 1
- [ ] Special Tank LV5  SLOT 2
- [ ] Special Tank LV5  SLOT 3
- [ ] Special Tank LV5  SLOT 4
- [ ] Special Tank LV5  SLOT 5
- [ ] Special Tank LV5  SLOT 6
- [ ] Special Tank LV6  SLOT 1
- [ ] Special Tank LV6  SLOT 2
- [ ] Special Tank LV6  SLOT 3
- [ ] Special Tank LV6  SLOT 4
- [ ] Special Tank LV6  SLOT 5
- [ ] Special Tank LV6  SLOT 6
- [ ] Special Tank LV7  SLOT 1
- [ ] Special Tank LV7  SLOT 2
- [ ] Special Tank LV7  SLOT 3
- [ ] Special Tank LV7  SLOT 4
- [ ] Special Tank LV7  SLOT 5
- [ ] Special Tank LV7  SLOT 6
- [ ] Special Tank LV8  SLOT 1
- [ ] Special Tank LV8  SLOT 2
- [ ] Special Tank LV8  SLOT 3
- [ ] Special Tank LV8  SLOT 4
- [ ] Special Tank LV8  SLOT 5
- [ ] Special Tank LV8  SLOT 6
- [ ] Special Tank LV9  SLOT 1
- [ ] Special Tank LV9  SLOT 2
- [ ] Special Tank LV9  SLOT 3
- [ ] Special Tank LV9  SLOT 4
- [ ] Special Tank LV9  SLOT 5
- [ ] Special Tank LV9  SLOT 6
- [ ] Special Tank LV10  SLOT 1
- [ ] Special Tank LV10  SLOT 2
- [ ] Special Tank LV10  SLOT 3
- [ ] Special Tank LV10  SLOT 4
- [ ] Special Tank LV10  SLOT 5
- [ ] Special Tank LV10  SLOT 6
- [ ] Special Tank LV11  SLOT 1
- [ ] Special Tank LV11  SLOT 2
- [ ] Special Tank LV11  SLOT 3
- [ ] Special Tank LV11  SLOT 4
- [ ] Special Tank LV11  SLOT 5
- [ ] Special Tank LV11  SLOT 6
